### ISSUE TITLE
Temperature sensor reading 0

### ISSUE THREAD

**Issue by mp1994** [ltebs-polimi/PSoC-I2C-Class#1]
Commit [350372c](https://github.com/ltebs-polimi/PSoC-I2C-Class/commit/350372cd96c65c5a59a192cd40b19993dc08d8ec) in the branch `solution` should fix the unexpected behavior of the temperature sensor, constantly reading 0. It is already merged in the `solution` branch, so it can be pulled and tested on the PSoC.
You can inspect the changes by clicking on the link above. Basically, the main difference is that we set `CTRL_REG1` to the value `0x47` to make sure the LIS3DH is turned on and configured with a 50 Hz sampling rate.

As mentioned during the class, the temperature sensor provides a **relative** temperature variation with respect to an unknown factory calibration value. See [here](https://community.st.com/s/question/0D50X00009XkfcT/how-to-understand-the-lis3dh-temperature-reading) for more details.

You can test the operation of the device by breathing on it. In case you still see a constant null output, you can try reading the register of the accelerometer in the `for(;;)` loop.

You may provide any feedback by commenting this Issue, or any fix you may find by opening a pull request.

**Comment by GiovanniParrella** [comment]
Thank you, it works for me!
